# 配置名称: Shadowrocket配置
# 配置作者: Centralmatrix3
# 更新时间: 26-09-05 00:00

[General]
# 启用IPv6
ipv6 = false

# 首选IPv6
prefer-ipv6 = false

# 接管模式
compatibility-mode = 3

# 私有应答
private-ip-answer = true

# ICMP自动回复
icmp-auto-reply = true

# QUIC屏蔽策略
block-quic = all-proxy

# 备用DNS服务器
fallback-dns-server = 223.5.5.5, 119.29.29.29

# 加密DNS服务器
dns-server = https://doh.pub/dns-query, https://dns.alidns.com/dns-query

# 直连域名使用系统DNS解析
dns-direct-system = false

# 直连域名解析失败使用代理
dns-direct-fallback-proxy = false

# 始终执行REJECT重写规则
always-reject-url-rewrite = false

# UDP回退策略
udp-policy-not-supported-behaviour = REJECT

# 更新配置文件
update-url = https://raw.githubusercontent.com/Centralmatrix3/Matrix-io/master/Config/Shadowrocket/Matrix.conf

[Proxy Group]
# 苹果服务
苹果服务 = select, DIRECT, PROXY, 自动选择, 香港节点, 台湾节点, 日本节点, 韩国节点, 狮城节点, 美国节点, policy-select-name=DIRECT

# 谷歌服务
谷歌服务 = select, PROXY, 自动选择, DIRECT, 香港节点, 台湾节点, 日本节点, 韩国节点, 狮城节点, 美国节点, policy-select-name=PROXY

# 国内媒体
国内媒体 = select, DIRECT, PROXY, 自动选择, 香港节点, 台湾节点, 日本节点, 韩国节点, 狮城节点, 美国节点, policy-select-name=DIRECT

# 国外媒体
国外媒体 = select, PROXY, 自动选择, DIRECT, 香港节点, 台湾节点, 日本节点, 韩国节点, 狮城节点, 美国节点, policy-select-name=PROXY

# 国外网站
国外网站 = select, PROXY, 自动选择, DIRECT, 香港节点, 台湾节点, 日本节点, 韩国节点, 狮城节点, 美国节点, policy-select-name=PROXY

# 黑白名单
黑白名单 = select, PROXY, 自动选择, DIRECT, 香港节点, 台湾节点, 日本节点, 韩国节点, 狮城节点, 美国节点, policy-select-name=PROXY

# 自动选择
自动选择 = url-test, interval=1800, tolerance=50, timeout=5, select=0, url=http://cp.cloudflare.com/generate_204, policy-regex-filter=^

# 香港节点
香港节点 = url-test, interval=1800, tolerance=50, timeout=5, select=0, url=http://cp.cloudflare.com/generate_204, policy-regex-filter=香港|港|HK|🇭🇰|(?i)Hong

# 台湾节点
台湾节点 = url-test, interval=1800, tolerance=50, timeout=5, select=0, url=http://cp.cloudflare.com/generate_204, policy-regex-filter=台湾|台|TW|🇹🇼|(?i)Taiwan

# 日本节点
日本节点 = url-test, interval=1800, tolerance=50, timeout=5, select=0, url=http://cp.cloudflare.com/generate_204, policy-regex-filter=日本|日|JP|🇯🇵|(?i)Japan

# 韩国节点
韩国节点 = url-test, interval=1800, tolerance=50, timeout=5, select=0, url=http://cp.cloudflare.com/generate_204, policy-regex-filter=韩国|韩|KR|🇰🇷|(?i)Korea

# 狮城节点
狮城节点 = url-test, interval=1800, tolerance=50, timeout=5, select=0, url=http://cp.cloudflare.com/generate_204, policy-regex-filter=新加坡|狮|SG|🇸🇬|(?i)Singapore

# 美国节点
美国节点 = url-test, interval=1800, tolerance=50, timeout=5, select=0, url=http://cp.cloudflare.com/generate_204, policy-regex-filter=美国|美|US|🇺🇸|(?i)States

[Rule]
# 规则修正
RULE-SET,https://raw.githubusercontent.com/Centralmatrix3/Matrix-io/master/Ruleset/Shadowrocket/Unbreak.list,DIRECT

# 广告拦截
RULE-SET,https://raw.githubusercontent.com/Centralmatrix3/Matrix-io/master/Ruleset/Shadowrocket/Advertising.list,REJECT

# 谷歌服务
RULE-SET,https://raw.githubusercontent.com/Centralmatrix3/Matrix-io/master/Ruleset/Shadowrocket/Google.list,谷歌服务

# 国外媒体
RULE-SET,https://raw.githubusercontent.com/Centralmatrix3/Matrix-io/master/Ruleset/Shadowrocket/GlobalMedia.list,国外媒体

# 国内媒体
RULE-SET,https://raw.githubusercontent.com/Centralmatrix3/Matrix-io/master/Ruleset/Shadowrocket/ChinaMedia.list,国内媒体

# 国外网站
RULE-SET,https://raw.githubusercontent.com/Centralmatrix3/Matrix-io/master/Ruleset/Shadowrocket/Global.list,国外网站

# 苹果服务
RULE-SET,https://raw.githubusercontent.com/Centralmatrix3/Matrix-io/master/Ruleset/Shadowrocket/Apple.list,苹果服务

# 局域网络
RULE-SET,https://raw.githubusercontent.com/Centralmatrix3/Matrix-io/master/Ruleset/Shadowrocket/LAN.list,DIRECT

# 国内网站
RULE-SET,https://raw.githubusercontent.com/Centralmatrix3/Matrix-io/master/Ruleset/Shadowrocket/GEOIPCN.list,DIRECT

# 最终规则
FINAL,黑白名单

[MITM]
# MitM over HTTP/2
h2 = true

# 主机名
hostname = -buy.itunes.apple.com
