#!name = AdBlock
#!desc = AdBlock合集
#!author = RuCu6、lodepuly、fmz200、Keywos、kokoryh

[URL Rewrite]
# 酷安
^https:\/\/api\.coolapk\.com\/v6\/search\?.*type=hotSearch - reject-dict

# 拼多多
^https:\/\/api\.(?:pinduoduo|yangkeduo)\.com\/api\/cappuccino\/splash\? - reject-dict
^https:\/\/api\.pinduoduo\.com\/api\/alexa\/goods\/back_up\? - reject-dict
^https:\/\/api\.pinduoduo\.com\/api\/brand-olay\/goods_detail\/bybt_guide - reject-dict
^https:\/\/api\.pinduoduo\.com\/api\/caterham\/v3\/query\/(?:likes|my_order_group|new_chat_group|order_express_group|personal) - reject-dict
^https:\/\/api\.pinduoduo\.com\/api\/engels\/reviews\/require\/append - reject-dict
^https:\/\/api\.pinduoduo\.com\/api\/flow\/hungary\/window\/global\/v2\? - reject-dict
^https:\/\/api\.pinduoduo\.com\/api\/zaire_biz\/chat\/resource\/get_list_data - reject-dict
^https:\/\/api\.pinduoduo\.com\/search_hotquery\? - reject-dict

# 小红书
^https:\/\/edith\.xiaohongshu\.com\/api\/sns\/(?:v2\/guide\/user_banner|v3\/note\/guide) - reject-dict
^https:\/\/edith\.xiaohongshu\.com\/api\/sns\/v1\/surprisebox\/(?:get_style|open|submit_action) - reject-dict
^https:\/\/www\.xiaohongshu\.com\/api\/marketing\/box\/trigger\? - reject-dict
^https:\/\/www\.xiaohongshu\.com\/api\/sns\/(?:v1\/ads\/resource|v2\/hey\/\w+\/hey_gallery) - reject-dict

# 微博国际版
^https?:\/\/api\.weibo\.cn\/\d\/(cardlist\?v_f=\d|ad\/weibointl\?) - reject-dict
^https?:\/\/weibointl\.api\.weibo\.cn\/portal\.php\?a=hot_search_users - reject-dict

[Script]
# 酷安
酷安 = type=http-response,pattern=^https:\/\/api\.coolapk\.com\/v6\/feed\/(detail|replyList)\?,script-path=https://raw.githubusercontent.com/RuCu6/QuanX/main/Scripts/coolapk.js,requires-body=true,timeout=60
酷安 = type=http-response,pattern=^https:\/\/api\.coolapk\.com\/v6\/main\/(dataList|indexV8|init),script-path=https://raw.githubusercontent.com/RuCu6/QuanX/main/Scripts/coolapk.js,requires-body=true,timeout=60
酷安 = type=http-response,pattern=^https:\/\/api\.coolapk\.com\/v6\/page\/dataList\?,script-path=https://raw.githubusercontent.com/RuCu6/QuanX/main/Scripts/coolapk.js,requires-body=true,timeout=60

# 拼多多
拼多多 = type=http-response,pattern=^https:\/\/api\.pinduoduo\.com\/api\/alexa\/homepage\/hub\?,script-path=https://raw.githubusercontent.com/RuCu6/Loon/main/Scripts/pdd.js,requires-body=true,timeout=60

# 小红书
小红书 = type=http-response,pattern=^https:\/\/edith\.xiaohongshu\.com\/api\/sns\/(?:v2\/note\/feed|v3\/note\/videofeed),script-path=https://raw.githubusercontent.com/RuCu6/Loon/main/Scripts/xiaohongshu.js,requires-body=true,timeout=60
小红书 = type=http-response,pattern=^https:\/\/edith\.xiaohongshu\.com\/api\/sns\/v1\/note\/(?:imagefeed|live_photo\/save),script-path=https://raw.githubusercontent.com/RuCu6/Loon/main/Scripts/xiaohongshu.js,requires-body=true,timeout=60
小红书 = type=http-response,pattern=^https:\/\/edith\.xiaohongshu\.com\/api\/sns\/v1\/search\/(?:banner|hot)_list,script-path=https://raw.githubusercontent.com/RuCu6/Loon/main/Scripts/xiaohongshu.js,requires-body=true,timeout=60
小红书 = type=http-response,pattern=^https:\/\/edith\.xiaohongshu\.com\/api\/sns\/v1\/system_service\/config\?,script-path=https://raw.githubusercontent.com/RuCu6/Loon/main/Scripts/xiaohongshu.js,requires-body=true,timeout=60
小红书 = type=http-response,pattern=^https:\/\/edith\.xiaohongshu\.com\/api\/sns\/v10\/search\/notes\?,script-path=https://raw.githubusercontent.com/RuCu6/Loon/main/Scripts/xiaohongshu.js,requires-body=true,timeout=60
小红书 = type=http-response,pattern=^https:\/\/edith\.xiaohongshu\.com\/api\/sns\/v2\/(?:note\/widgets|user\/followings\/followfeed),script-path=https://raw.githubusercontent.com/RuCu6/Loon/main/Scripts/xiaohongshu.js,requires-body=true,timeout=60
小红书 = type=http-response,pattern=^https:\/\/edith\.xiaohongshu\.com\/api\/sns\/v2\/system_service\/splash_config,script-path=https://raw.githubusercontent.com/RuCu6/Loon/main/Scripts/xiaohongshu.js,requires-body=true,timeout=60
小红书 = type=http-response,pattern=^https:\/\/edith\.xiaohongshu\.com\/api\/sns\/v4\/followfeed\?,script-path=https://raw.githubusercontent.com/RuCu6/Loon/main/Scripts/xiaohongshu.js,requires-body=true,timeout=60
小红书 = type=http-response,pattern=^https:\/\/edith\.xiaohongshu\.com\/api\/sns\/v4\/search\/(?:hint|trending),script-path=https://raw.githubusercontent.com/RuCu6/Loon/main/Scripts/xiaohongshu.js,requires-body=true,timeout=60
小红书 = type=http-response,pattern=^https:\/\/edith\.xiaohongshu\.com\/api\/sns\/v5\/recommend\/user\/follow_recommend\?,script-path=https://raw.githubusercontent.com/RuCu6/Loon/main/Scripts/xiaohongshu.js,requires-body=true,timeout=60
小红书 = type=http-response,pattern=^https:\/\/edith\.xiaohongshu\.com\/api\/sns\/v6\/homefeed\?,script-path=https://raw.githubusercontent.com/RuCu6/Loon/main/Scripts/xiaohongshu.js,requires-body=true,timeout=60

# 微博国际版
微博国际版 = type=http-response,pattern=^https?:\/\/api\.weibo\.cn\/\d\/statuses\/.*timeline,script-path=https://raw.githubusercontent.com/Keywos/rule/master/script/weibo_us/js/index.js,requires-body=true,timeout=60
微博国际版 = type=http-response,pattern=^https?:\/\/sdkapp\.uve\.weibo\.com\/interface\/sdk\/sdkad\.php,script-path=https://raw.githubusercontent.com/Keywos/rule/master/script/weibo_us/js/index.js,requires-body=true,timeout=60
微博国际版 = type=http-response,pattern=^https?:\/\/weibointl\.api\.weibo\.cn\/portal\.php\?(ct=(feed&a=trends|user&a=get_searching_info)|a=(get_coopen_ads|user_center|search_topic|open_app&auth|icon_center)),script-path=https://raw.githubusercontent.com/Keywos/rule/master/script/weibo_us/js/index.js,requires-body=true,timeout=60

[MITM]
hostname = %APPEND% api.coolapk.com, api.pinduoduo.com, api.yangkeduo.com, edith.xiaohongshu.com, www.xiaohongshu.com, *api.weibo.cn, sdkapp.uve.weibo.com