#!name = 哔哩哔哩
#!desc = 哔哩哔哩去广告
#!author = RuCu6、Maasea、kokoryh、lodepuly

[URL Rewrite]
^http:\/\/[\d\.]+:8000\/v1\/resource\/\w{32}-1-SPLASH - reject-dict

^http:\/\/upos-sz-static\.bilivideo\.com\/ssaxcode\/\w{2}\/\w{2}\/\w{32}-1-SPLASH - reject-dict

^https:\/\/(?:api\.bilibili\.com\/x\/mengqi\/v1\/resource|app\.bilibili\.com\/x\/resource\/peak\/download) - reject-dict

^https:\/\/(?:app\.bilibili\.com|grpc\.biliapi\.net)\/bilibili\.app\.interface\.v1\.Search\/DefaultWords - reject-dict

^https:\/\/(?:app\.bilibili\.com|grpc\.biliapi\.net)\/bilibili\.app\.view\.v1\.View\/TFInfo - reject-dict

^https:\/\/api\.bilibili\.com\/x\/v2\/dm\/qoe\/show\? - reject-dict

^https:\/\/api\.bilibili\.com\/x\/vip\/ads\/materials\? - reject-dict

^https:\/\/api\.bilibili\.com\/x\/web-interface\/zone\?jsonp - reject-dict

^https:\/\/api\.live\.bilibili\.com\/xlive\/e-commerce-interface\/v1\/ecommerce-user\/get_shopping_info\? - reject-dict

^https:\/\/app\.bilibili\.com\/x\/resource\/ip - reject-dict

[Script]
哔哩哔哩 = type=http-response,pattern=^https:\/\/(?:app\.bilibili\.com|grpc\.biliapi\.net)\/bilibili\.app\.(?:view|viewunite)\.v1\.View\/(?:View|ViewProgress)$,script-path=https://raw.githubusercontent.com/Centralmatrix3/Scripts/master/Scripts/BiliBili/ProtoC.js,requires-body=true,binary-body-mode=true,timeout=60

哔哩哔哩 = type=http-response,pattern=^https:\/\/(?:app\.bilibili\.com|grpc\.biliapi\.net)\/bilibili\.app\.dynamic\.v2\.Dynamic\/DynAll$,script-path=https://raw.githubusercontent.com/Centralmatrix3/Scripts/master/Scripts/BiliBili/ProtoC.js,requires-body=true,binary-body-mode=true,timeout=60

哔哩哔哩 = type=http-response,pattern=^https:\/\/(?:app\.bilibili\.com|grpc\.biliapi\.net)\/bilibili\.app\.interface\.v1\.Teenagers\/ModeStatus,script-path=https://raw.githubusercontent.com/Centralmatrix3/Scripts/master/Scripts/BiliBili/ProtoC.js,requires-body=true,binary-body-mode=true,timeout=60

哔哩哔哩 = type=http-response,pattern=^https:\/\/(?:app\.bilibili\.com|grpc\.biliapi\.net)\/bilibili\.app\.show\.v1\.Popular\/Index$,script-path=https://raw.githubusercontent.com/Centralmatrix3/Scripts/master/Scripts/BiliBili/ProtoC.js,requires-body=true,binary-body-mode=true,timeout=60

哔哩哔哩 = type=http-response,pattern=^https:\/\/(?:app\.bilibili\.com|grpc\.biliapi\.net)\/bilibili\.community\.service\.dm\.v1\.DM\/DmSegMobile,script-path=https://raw.githubusercontent.com/Centralmatrix3/Scripts/master/Scripts/BiliBili/ProtoC.js,requires-body=true,binary-body-mode=true,timeout=60

哔哩哔哩 = type=http-response,pattern=^https:\/\/(?:app\.bilibili\.com|grpc\.biliapi\.net)\/bilibili\.community\.service\.dm\.v1\.DM\/DmView,script-path=https://raw.githubusercontent.com/Centralmatrix3/Scripts/master/Scripts/BiliBili/ProtoC.js,requires-body=true,binary-body-mode=true,timeout=60

哔哩哔哩 = type=http-response,pattern=^https:\/\/(?:app\.bilibili\.com|grpc\.biliapi\.net)\/bilibili\.main\.community\.reply\.v1\.Reply\/MainList,script-path=https://raw.githubusercontent.com/Centralmatrix3/Scripts/master/Scripts/BiliBili/ProtoC.js,requires-body=true,binary-body-mode=true,timeout=60

哔哩哔哩 = type=http-response,pattern=^https:\/\/(?:app\.bilibili\.com|grpc\.biliapi\.net)\/bilibili\.polymer\.app\.search\.v1\.Search\/SearchAll$,script-path=https://raw.githubusercontent.com/Centralmatrix3/Scripts/master/Scripts/BiliBili/ProtoC.js,requires-body=true,binary-body-mode=true,timeout=60

哔哩哔哩 = type=http-response,pattern=^https:\/\/api\.bilibili\.com\/pgc\/page\/(?:bangumi|cinema\/tab),script-path=https://raw.githubusercontent.com/Centralmatrix3/Scripts/master/Scripts/BiliBili/JSON.js,requires-body=true,timeout=60

哔哩哔哩 = type=http-response,pattern=^https:\/\/api\.live\.bilibili\.com\/xlive\/app-room\/v1\/index\/getInfoByRoom\?,script-path=https://raw.githubusercontent.com/Centralmatrix3/Scripts/master/Scripts/BiliBili/JSON.js,requires-body=true,timeout=60

哔哩哔哩 = type=http-response,pattern=^https:\/\/app\.bilibili\.com\/x\/resource\/show\/skin\?,script-path=https://raw.githubusercontent.com/Centralmatrix3/Scripts/master/Scripts/BiliBili/JSON.js,requires-body=true,timeout=60

哔哩哔哩 = type=http-response,pattern=^https:\/\/app\.bilibili\.com\/x\/resource\/show\/tab\/v2\?,script-path=https://raw.githubusercontent.com/Centralmatrix3/Scripts/master/Scripts/BiliBili/JSON.js,requires-body=true,timeout=60

哔哩哔哩 = type=http-response,pattern=^https:\/\/app\.bilibili\.com\/x\/resource\/top\/activity\?,script-path=https://raw.githubusercontent.com/Centralmatrix3/Scripts/master/Scripts/BiliBili/JSON.js,requires-body=true,timeout=60

哔哩哔哩 = type=http-response,pattern=^https:\/\/app\.bilibili\.com\/x\/v2\/account\/(?:mine(\/ipad)?|myinfo),script-path=https://raw.githubusercontent.com/Centralmatrix3/Scripts/master/Scripts/BiliBili/JSON.js,requires-body=true,timeout=60

哔哩哔哩 = type=http-response,pattern=^https:\/\/app\.bilibili\.com\/x\/v2\/feed\/index(\/story)?\?,script-path=https://raw.githubusercontent.com/Centralmatrix3/Scripts/master/Scripts/BiliBili/JSON.js,requires-body=true,timeout=60

哔哩哔哩 = type=http-response,pattern=^https:\/\/app\.bilibili\.com\/x\/v2\/search\/square\?,script-path=https://raw.githubusercontent.com/Centralmatrix3/Scripts/master/Scripts/BiliBili/JSON.js,requires-body=true,timeout=60

哔哩哔哩 = type=http-response,pattern=^https:\/\/app\.bilibili\.com\/x\/v2\/splash\/(?:brand\/list|event\/list2|list|show),script-path=https://raw.githubusercontent.com/Centralmatrix3/Scripts/master/Scripts/BiliBili/JSON.js,requires-body=true,timeout=60

[MITM]
hostname = %APPEND% ap*.bilibili.com, grpc.biliapi.net, www.bilibili.com, m.bilibili.com, *live.bilibili.com