#!name = BoxJs
#!desc = http://boxjs.com
#!author = chavyleung

[General]
force-http-engine-hosts = %APPEND% boxjs.com, boxjs.net, *.boxjs.com, *.boxjs.net

[Script]
BoxJs = type=http-request,pattern=^https?:\/\/(.+\.)?boxjs\.(com|net),script-path=https://raw.githubusercontent.com/chavyleung/scripts/master/box/chavy.boxjs.js,requires-body=true,timeout=120

[MITM]
hostname = %APPEND% boxjs.com, boxjs.net, *.boxjs.com, *.boxjs.net