#!name = 网易云音乐
#!desc = 网易云音乐去广告
#!author = RuCu6、Keywos

[URL Rewrite]
^https:\/\/interface3?\.music\.163\.com\/eapi\/(ios\/version|mlivestream\/entrance\/playpage\/|link\/position\/show\/strategy|link\/scene\/show\/resource|v1\/content\/exposure\/comment\/banner\/) - reject-dict

^https:\/\/interface3?\.music\.163\.com\/eapi\/(music-vip-membership\/client\/vip\/info|vipauth\/app\/auth\/recycle) - reject-dict

^https?:\/\/interface3?\.music\.163\.com\/e?api\/(ocpc\/)?ad\/ - reject-dict

^https?:\/\/interface3?\.music\.163\.com\/eapi\/(community\/friends\/fans-group\/artist\/group\/|mine\/applet\/redpoint|music\/songshare\/text\/recommend\/|resniche\/position\/play\/new\/|resource\/comments?\/musiciansaid\/|user\/sub\/artist) - reject-dict

^https?:\/\/interface3?\.music\.163\.com\/eapi\/(content\/activity\/music\/|delivery\/(batch-deliver|deliver)|moment\/tab\/info\/|side-bar\/mini-program\/music-service\/account|yunbei\/account\/entrance\/) - reject-dict

^https?:\/\/interface3?\.music\.163\.com\/w?eapi\/(activity\/bonus\/playpage\/time\/query|resource-exposure\/|search\/(chart\/|default\/|rcmd\/keyword\/|specialkeyword\/)) - reject-dict

[Script]
网易云音乐 = type=http-response,pattern=^https:\/\/interface3?\.music\.163\.com\/eapi\/(batch|v2\/resource\/comment\/floor\/),script-path=https://raw.githubusercontent.com/Keywos/rule/main/JS/wyresParam_nolog.js,requires-body=true,binary-body-mode=true,timeout=60

网易云音乐 = type=http-response,pattern=^https:\/\/interface3?\.music\.163\.com\/eapi\/(homepage\/block\/page|link\/page\/rcmd\/(block\/resource\/multi\/refresh|resource\/show)),script-path=https://raw.githubusercontent.com/Keywos/rule/main/JS/wyresParam_nolog.js,requires-body=true,binary-body-mode=true,timeout=60

网易云音乐 = type=http-response,pattern=^https:\/\/interface3?\.music\.163\.com\/eapi\/(music-vip-membership\/client\/vip\/info|vipauth\/app\/auth\/recycle),script-path=https://raw.githubusercontent.com/Keywos/rule/main/JS/wyresParam_nolog.js,requires-body=true,binary-body-mode=true,timeout=60

网易云音乐 = type=http-response,pattern=^https:\/\/interface3?\.music\.163\.com\/eapi\/link\/home\/framework\/tab,script-path=https://raw.githubusercontent.com/Keywos/rule/main/JS/wyresParam_nolog.js,requires-body=true,binary-body-mode=true,timeout=60

网易云音乐 = type=http-response,pattern=^https:\/\/interface3?\.music\.163\.com\/eapi\/link\/page\/discovery\/resource\/show,script-path=https://raw.githubusercontent.com/Keywos/rule/main/JS/wyresParam_nolog.js,requires-body=true,binary-body-mode=true,timeout=60

网易云音乐 = type=http-response,pattern=^https:\/\/interface3?\.music\.163\.com\/eapi\/link\/position\/show\/resource,script-path=https://raw.githubusercontent.com/Keywos/rule/main/JS/wyresParam_nolog.js,requires-body=true,binary-body-mode=true,timeout=60

网易云音乐 = type=http-response,pattern=^https:\/\/interface3?\.music\.163\.com\/eapi\/song\/play\/more\/list\/,script-path=https://raw.githubusercontent.com/Keywos/rule/main/JS/wyresParam_nolog.js,requires-body=true,binary-body-mode=true,timeout=60

网易云音乐 = type=http-response,pattern=^https:\/\/interface3?\.music\.163\.com\/eapi\/user\/follow\/users\/mixed\/,script-path=https://raw.githubusercontent.com/Keywos/rule/main/JS/wyresParam_nolog.js,requires-body=true,binary-body-mode=true,timeout=60

[MITM]
hostname = %APPEND% interface*.music.163.com