#!name = 虎牙
#!desc = 虎牙去广告
#!author = fmz200

[URL Rewrite]
^http:\/\/cdn\.wup\.huya\.com\/launch\/queryHttpDns$ - reject

^https?:\/\/business\.msstatic\.com\/advertiser\/material - reject

^https?:\/\/cdnfile1\.msstatic\.com\/cdnfile\/appad\/ - reject-img

^https?:\/\/live-ads\.huya\.com\/live\/getAllEntrance.*$ - reject-dict

[MITM]
hostname = %APPEND% business.msstatic.com, cdn.wup.huya.com, cdnfile1.msstatic.com, live-ads.huya.com