#!name = 美团
#!desc = 美团去广告
#!author = fmz200

[URL Rewrite]
^http:\/\/s3plus\.meituan\.net\/.*\/brandcpt-vedio\/.*\?time - reject

^http:\/\/wmapi\.meituan\.com\/api\/v7\/(loadInfo|openscreen|startpicture)\? - reject-dict

^https:\/\/cdb\.meituan\.com\/marketing\/source\/getPageSlotList - reject-dict

^https?:\/\/(s3plus|flowplus)\.meituan\.net\/v\d\/\w+\/linglong\/\w+\.(gif|jpg|mp4) - reject

^https?:\/\/apimobile\.meituan\.com\/appupdate\/mach\/checkUpdate? - reject

^https?:\/\/flowplus\.meituan\.net\/v\d\/\w+\/linglong\/\d+\.(gif|jpg|mp4) - reject

^https?:\/\/img\.meituan\.net\/(?>adunion|display|midas)\/.+?\.(gif|jpg|jpg\.webp)$ - reject-200

^https?:\/\/img\.meituan\.net\/(adunion|display|midas)\/\w+\.(gif|jpg|jpg\.webp)$ - reject

^https?:\/\/img\.meituan\.net\/(bizad|brandCpt)\/\w+\.(png|jpg) - reject

^https?:\/\/img\.meituan\.net\/bizad\/.*.jpg - reject-200

^https?:\/\/p\d.meituan.net\/movie\/.*?\?may_covertWebp - reject-img

^https?:\/\/p\d\.meituan\.net\/movie\/[A-Za-z0-9]+?\.jpg\?may_covertWebp - reject-200

^https?:\/\/p\d\.meituan\.net\/wmbanner\/[A-Za-z0-9]+?\.jpg - reject-200

^https?:\/\/p\d{1}\.meituan\.net\/(adunion|display|mmc|wmbanner)\/ - reject

^https?:\/\/peisongapi\.meituan\.com\/client\/getInitiateImage - reject-200

^https?:\/\/s3plus\.meituan\.net\/.+?\/linglong\/ - reject

^https?:\/\/s3plus\.meituan\.net\/v1\/mss_a002 - reject-img

^https?:\/\/wmapi\.meituan\.com\/api\/v\d\/startpicture - reject

^https?:\/\/wmapi\.meituan\.com\/api\/v\d+\/loadInfo\? - reject

^https?:\/\/www\.meituan\.com\/api\/v\d\/appstatus\? - reject

[MITM]
hostname = %APPEND% apimobile.meituan.net, cdb.meituan.com, flowplus.meituan.net, img.meituan.net, p*.meituan.net, peisongapi.meituan.com, s3plus.meituan.net, wmapi.meituan.com, wmapi.meituan.net, www.meituan.net