#!name = TestFlight
#!desc = TestFlight强制安装
#!author = Skyxim

[Script]
TF强制安装 = type=http-response,pattern=^https:\/\/testflight\.apple\.com((\/v3\/accounts\/.+?\/apps$)|(\/v2\/accounts\/.+?\/apps\/.+?\/builds\/.+)),script-path=https://raw.githubusercontent.com/Centralmatrix3/Matrix-io/master/Shadowrocket/Scripts/TestFlightX.js,requires-body=true,timeout=120

[MITM]
hostname = %APPEND% testflight.apple.com