#!name = YouTube
#!desc = YouTube去广告
#!author = Maasea、RuCu6

[URL Rewrite]
^https:\/\/[\w-]+\.googlevideo\.com\/initplayback\?.+&oad - reject-dict

[Script]
YouTube = type=http-request,pattern=^https:\/\/youtubei\.googleapis\.com\/youtubei\/v1\/(browse|next|player|reel\/reel_watch_sequence)\?,script-path=https://raw.githubusercontent.com/RuCu6/QuanX/main/Scripts/youtube-request.js,requires-body=true,binary-body-mode=true,timeout=60

YouTube = type=http-response,pattern=^https:\/\/youtubei\.googleapis\.com\/youtubei\/v1\/(browse|next|player|search|reel\/reel_watch_sequence|guide|account\/get_setting)\?,script-path=https://raw.githubusercontent.com/RuCu6/QuanX/main/Scripts/youtube-response.js,requires-body=true,binary-body-mode=true,timeout=60

[MITM]
hostname = %APPEND% rr*.googlevideo.com, youtubei.googleapis.com