name: Build

on:
  workflow_dispatch:
  schedule:
    - cron: "5 0,12 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SINGBOX_VERSION: "1.14.0"
      TZ: "Asia/Shanghai"
      PYTHONPATH: "Network/Scripts"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7.0.1

      - name: Checkout Repository
        uses: actions/checkout@v7.0.1
        with:
          repository: Centralmatrix3/Network
          path: Network

      - name: Sources Sync
        run: |
          python -m Build S Matrix-io --copy

      - name: Convert Rule
        run: |
          for dir in Ruleset/Egern; do
            [ ! -d "$dir" ] && echo "$dir Not Found." && continue
            python -m Build C Surge Egern "$dir"
          done
          for dir in Ruleset/QuantumultX; do
            [ ! -d "$dir" ] && echo "$dir Not Found." && continue
            python -m Build C Surge QuantumultX "$dir"
          done
          for dir in Ruleset/Sing-box; do
            [ ! -d "$dir" ] && echo "$dir Not Found." && continue
            python -m Build C Surge Singbox "$dir"
          done
          for dir in Ruleset/{Clash,Stash}; do
            [ ! -d "$dir" ] && echo "$dir Not Found." && continue
            python -m Build C Surge Stash "$dir"
          done
          for dir in Ruleset/{Loon,Shadowrocket,Surge}; do
            [ ! -d "$dir" ] && echo "$dir Not Found." && continue
            python -m Build C Surge Surge "$dir"
          done

      - name: Compile Rule
        run: |
          curl -fsSL -o sing-box.tar.gz "https://github.com/SagerNet/sing-box/releases/download/v${SINGBOX_VERSION}/sing-box-${SINGBOX_VERSION}-linux-amd64.tar.gz"
          tar -xzf sing-box.tar.gz
          chmod +x "sing-box-${SINGBOX_VERSION}-linux-amd64/sing-box"
          sudo mv "sing-box-${SINGBOX_VERSION}-linux-amd64/sing-box" /usr/local/bin/sing-box
          sing-box version
          for file in Ruleset/Sing-box/*.json; do
            [ ! -f "$file" ] && echo "$file Not Found." && continue
            sing-box rule-set compile "$file" -o "${file%.json}.srs"
          done
          rm -rf Network sing-box.tar.gz sing-box-*-linux-amd64

      - name: Push Changes
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config --local user.email "${{ github.actor }}@users.noreply.github.com"
            git config --local user.name "${{ github.actor }}"
            git add -A
            git commit -m "$(date +'%Y-%m-%d %H:%M:%S')"
            git push origin master
          else
            echo "No Repository Update Detected."
          fi

      - name: Delete Workflow Run
        uses: Mattraks/delete-workflow-runs@main
        with:
          retain_days: 0
          keep_minimum_runs: 2
